### PR TITLE
Added Gen 4 Support

### PR DESCRIPTION
**Pull request by ZVelasco**
Credit to Ilúvatar on Discord from Eureka,CA

### CODE REVIEW

**Comment by cub01d** [comment]
I think we can merge these in for now, but there's no fast/charge moves. @mralanlee ?

**Comment by Alterraia** [comment]
Pokemon Go Hub doesn't have any of the fast/charge moves listed.  But your current version of pokemon.json also didn't have the moves for gen 3, which I added, unless I just never updated.

I also corrected the pokemon numbers so that each pokemon has their dex # instead of being off by 1.

In addition to this, in case a zero was required, I added MissingNo as the 0 placeholder.

I'm currently updating pokemon.json with the new stats for all of the pokemon, as well as cp.json, which I'll send over to ZValasco when I'm done.  Takes a while, but it will be done.

**Comment by Alterraia** [comment]
Oh btw, the update also includes alolan forms.  Not certain if you wanted to include them, but they are there, making it possible for the bot to recognize alolan_exeggutor or alolan_marowak.

**Comment by mralanlee** [comment]
This will need to be refactored significantly in the future. Too many items inside the array and it'll be a burden on memory usage.

**Pull request merged**
