### PR TITLE
!raid command support "exgym"; !cp updated with gen3, weather, lvl25 stats

### PR DESCRIPTION
**Pull request by pbk01**
This adds basic functionality to detect specific SPECIALRAIDS keywords and apply the tags (e.g. @sponsored, @park). While sponsored was a desired functionality, I added park due to the recent EX Raid pass emphasis on parks.

 Updated README.md for setup of 'sponsored' and 'park' roles
 Updated raid.js
   Revised warning messages to match new command syntax
   Added section to detect optional parameter keyWords
   Revised location details parsing to adjust for any detected keyWords
 Updated constants.js
   Added SPECIALRAIDS consants for the 'sponsored', 'park' parameters.

### CODE REVIEW

**Comment by pbk01** [comment]
Added gen 3 raid bosses and weather affected raid boss lvl25 cp data with corresponding weather. Restructured the JSON for the additional data, and re-wrote the !cp output.

**Comment by adorableducky** [comment]
It sounds like this would address the manual @ tagging we currently do (which redwood garbles if included in the raid report).  Can we add exgym as a SPECIALRAIDS  constant  too?  Mods have a request to rename the @sponsored tag to @exgym and to be used only for locations that have had past ex raids. This would simplify notifications so that people only sign up for one notification instead of both @sponsored and @park.  We tried renaming the sponsored role to exgym but it breaks professor redwood for assignments (will assign @exgym when running !want sponsored but not !want exgym, and rerunning !want sponsored does not remove the exgym role). Can you help us update the bot with this change? Thank you!

**Comment by sponsored** [comment]
Hey guys. @sponsored here. Did you know I'm more than just a tag? The magic of your issue has brought me to life (much like Pinocchio, apparently he also used to get sick of emails from people unimaginatively co-opting his name too) 😉

**Comment by adorableducky** [comment]
Apologies, lesson learned. I will be more careful from now on and not tag by accident. Thanks for the heads up!

**Comment by sponsored** [comment]
No problems - I'm just teasing you guys. Good luck with the project 😉

**Comment by pbk01** [comment]
@adorableducky Do I correctly understand the the desire is to use @exgym as the only SPECIALRAID tag (removing @ sponsored and @ park tags and functionality)? As I designed it, the functionality would be as such:
  "!want exgym" = assign tag
  "!raid <boss> <time> exgym <location>" = invoke the alert with the special @exgym tag

**Comment by pbk01** [comment]
Darnit... the above used <> tags, which were removed.
  "!raid [boss] [time] exgym [location]" = invoke the alert with the special @exgym tag

**Comment by pbk01** [comment]
And to clarify, with the code as-is in this pull request, adding "exgym" to the SPECIALRAIDS constants (and removing "sponsored", "park") should work without any modifications to the code as long as the role "@exgym" is already configured in the Discord server. I will test later tonight.

**Comment by pbk01** [comment]
New commit fixes the problem with !want command recognizing SPECIALRAIDS constants. All files updated for 'exraid' tag usage.

**Comment by mralanlee** [comment]
@pbk01 sorry for the delay, merged.

**Pull request merged**
