### PR TITLE
Unable to adjust time difference.

### PR DESCRIPTION
**Pull request by Alterraia**
I run 2 versions of the bot off of a Raspberry Pi.  The Pi is located in CA and uses local PST.  No issues with that bot, Professor Sequoia.

I moved Maryland, so I'm on EST, and there's no organized PoGo group here.  So, I cloned the bot, made the changes like I did for Sequoia, to work for this area.

Problem is, that when running !egg or !raid command, the bot replies with a time from PST.

I combed through all bot files searching for "date" and "time", and found 2 files which might have an impact:

node_modules > discord.js > src > client > rest > RequestHandlers > Burst.js and Sequential.js

They both have something that says:

* The time difference between Discord's Dates and the local computer's Dates. A positive number means the local
* computer's time is ahead of Discord's

And below that:

this.timeDifference = 0;

I thought that if I changed the 0 to a 3, that would be enough, but the bot running for MD is still using PST.

Is there something more I need to do for it to register the time difference?

Is there something I can add that will make the difference?

This is the one thing holding me back from going live.

### CODE REVIEW

**Comment by cub01d** [comment]
That might be an issue with the way we get our timestamp since that's configured to the system time. Is your Maryland bot running on the same pi?

Also, closing this PR, since this is more of a discussion (issue).

**Comment by Alterraia** [comment]
Yes, it's running on the same Pi because there's plenty of space there.  I
didn't want my Eureka group to be offline for a week while I moved.

I was hoping that the system time, being PST, just needed to have the time
difference added, giving it the +3 needed.

**Comment by pbk01** [comment]
The Date() object used in the !egg and !raid commands is core javascript, and I don't think it is affected by any setting in the discord.js package. Since Date() .getHours() and .getMinutes() methods use the Pi local timezone, I would recommend incorporating a timezone offset into the constants.js data object and re-writing the format_time function to incorporate .getUTCHours() and the timezone offset.

**Comment by Alterraia** [comment]
date.setHours( date.getHours() + 3 );


Was the resolution Slackey found.  Entered under line 82 in raid.js and
line 74 in egg.js.


This will resolve any time issues or should.


Thanks for feedback.

**Pull request closed without merging**
